#!/bin/bash
set -euo pipefail

# UOS App Store compliant deb package builder
# Reference: https://uosdn.uniontech.com/#document3?dirid=656ef27dbd766615b0b0300e&id=65702eaebd766615b0b0310d

APPID="com.github.dbusworkbench"
APP_NAME="D-Bus Workbench"
VERSION="1.0.0"
ARCH="amd64"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BUILD_DIR="$PROJECT_ROOT/dist/uos-build"
DEB_DIR="$BUILD_DIR/${APPID}"

echo "=== Building UOS compliant deb package ==="
echo "AppID: ${APPID}"
echo "Version: ${VERSION}"
echo "Arch: ${ARCH}"

# Step 1: Build the Electron app (unpacked)
echo ""
echo "[1/6] Building Electron app..."
cd "$PROJECT_ROOT"
npm run build:vite
npx electron-builder --linux dir --x64

UNPACKED_DIR="$PROJECT_ROOT/dist/linux-unpacked"
if [ ! -d "$UNPACKED_DIR" ]; then
    echo "ERROR: Electron build output not found at $UNPACKED_DIR"
    exit 1
fi

# Step 2: Create UOS directory structure
echo ""
echo "[2/6] Creating UOS directory structure..."
rm -rf "$BUILD_DIR"
mkdir -p "$DEB_DIR/entries/applications"
mkdir -p "$DEB_DIR/entries/icons/hicolor/scalable/apps"
mkdir -p "$DEB_DIR/files"

# Sizes required by UOS: 16/24/32/48/128/256/512
for size in 16 24 32 48 128 256 512; do
    mkdir -p "$DEB_DIR/entries/icons/hicolor/${size}x${size}/apps"
done

# Step 3: Copy application files to files/
echo ""
echo "[3/6] Copying application files..."
cp -a "$UNPACKED_DIR"/. "$DEB_DIR/files/"

# Remove the default desktop file generated by electron-builder
rm -f "$DEB_DIR/files/dbus-workbench-electron.desktop" 2>/dev/null || true

# Step 4: Create desktop file
echo ""
echo "[4/6] Creating desktop file..."
cat > "$DEB_DIR/entries/applications/${APPID}.desktop" << 'DESKTOP'
[Desktop Entry]
Categories=Development;
Name=D-Bus Workbench
Name[zh_CN]=D-Bus 工作台
Comment=Modern D-Bus introspection tool
Comment[zh_CN]=现代化 D-Bus 内省工具
Keywords=dbus;debug;introspection;ipc;linux;system;
Keywords[zh_CN]=dbus;调试;内省;ipc;系统;
Exec=/opt/apps/com.github.dbusworkbench/files/dbus-workbench-electron %U
Icon=com.github.dbusworkbench
Type=Application
Terminal=false
StartupWMClass=dbus-workbench-electron
StartupNotify=true
DESKTOP

# Step 5: Copy icons
echo ""
echo "[5/6] Copying icons..."
ICONS_SRC="$PROJECT_ROOT/assets/icons/png"

# Copy PNG icons to matching resolution dirs
for size in 16 24 32 48 128 256 512; do
    src="$ICONS_SRC/${size}x${size}.png"
    if [ -f "$src" ]; then
        cp "$src" "$DEB_DIR/entries/icons/hicolor/${size}x${size}/apps/${APPID}.png"
    else
        echo "WARN: Missing icon size ${size}x${size}, skipping"
    fi
done

# Copy SVG if available
SVG_SRC="$PROJECT_ROOT/assets/icons/app-icon.svg"
if [ -f "$SVG_SRC" ]; then
    cp "$SVG_SRC" "$DEB_DIR/entries/icons/hicolor/scalable/apps/${APPID}.svg"
fi

# Step 6: Create info file
echo ""
echo "[6/6] Creating info file..."
cat > "$DEB_DIR/info" << INFO
{
    "appid": "${APPID}",
    "name": "${APP_NAME}",
    "version": "${VERSION}",
    "arch": ["${ARCH}"],
    "permissions": {
        "autostart": false,
        "notification": false,
        "trayicon": false,
        "clipboard": true,
        "account": false,
        "bluetooth": false,
        "camera": false,
        "audio_record": false,
        "installed_apps": false
    }
}
INFO

# Build DEBIAN directory
DEBIAN_DIR="$BUILD_DIR/DEBIAN"
mkdir -p "$DEBIAN_DIR"

# Create control file
INSTALLED_SIZE=$(du -sk "$DEB_DIR" | cut -f1)
cat > "$DEBIAN_DIR/control" << CONTROL
Package: ${APPID}
Version: ${VERSION}
Section: devel
Priority: optional
Architecture: ${ARCH}
Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, libsecret-1-0
Installed-Size: ${INSTALLED_SIZE}
Maintainer: YinJie <yj.watermelon@gmail.com>
Homepage: https://github.com/waterlovemelon/dbus-workbench
Description: Modern D-Bus introspection, method invocation, and signal monitoring tool
 D-Bus Workbench is a developer tool for introspecting D-Bus services,
 invoking methods, monitoring signals, and inspecting properties on
 Linux systems using both local and remote (SSH) connections.
CONTROL

# UOS spec: postinst/postrm must NOT modify system files.
# The entries/ directory auto-maps to /usr/share/ on install.
# No hook scripts needed for UOS compliance.
# Create empty DEBIAN dir with control only.

# Build the deb package
OUTPUT_DEB="$PROJECT_ROOT/dist/${APPID}_${VERSION}_${ARCH}.deb"
echo ""
echo "Building deb package..."
dpkg-deb --root-owner-group -b "$BUILD_DIR" "$OUTPUT_DEB"

echo ""
echo "=== UOS deb package built successfully ==="
echo "Output: $OUTPUT_DEB"
echo ""
echo "Verifying package..."
dpkg-deb -I "$OUTPUT_DEB"
echo ""
echo "Package contents (first 20 entries):"
dpkg-deb -c "$OUTPUT_DEB" | head -20

# Cleanup
echo ""
echo "Cleaning up build directory..."
rm -rf "$BUILD_DIR"

echo "Done."
